global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'ingredient_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ingredient-service:8080']
        labels:
          application: 'Ingredient Service Application'
  - job_name: 'kafka_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['kafka-service:8080']
        labels:
          application: 'Kafka Service Application'
  - job_name: 'recipe-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['recipe-service:8080']
        labels:
          application: 'Recipe Service Application'
